services:
  postgres:
    image: postgres:18
    container_name: adivinhe-o-ano-db
    restart: unless-stopped

    environment:
      POSTGRES_DB: adivinhe_ano
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: